### ISSUE TITLE
Please include an open source LICENSE for this project

### ISSUE THREAD

**Issue by avamk** [ploopyco/classic-trackball#1]
Super cool project!

But please include a LICENSE for this repository, such as [The TAPR Open Hardware License ("OHL")](https://en.wikipedia.org/wiki/TAPR_Open_Hardware_License) or the [CERN Open Hardware License](https://en.wikipedia.org/wiki/CERN_Open_Hardware_License).

**Comment by ploopyco** [comment]
The hardware license is located at https://github.com/ploopyco/mouse/blob/master/hardware/LICENSE (CERN). The firmware license is located at https://github.com/ploopyco/mouse/blob/master/firmware/LICENSE (GPL).
