### ISSUE TITLE
sourcing pmw 3360

### ISSUE THREAD

**Issue by synaption** [ploopyco/classic-trackball#13]
I am having a hard time sourcing this sensor.  would you mind sharing where you are getting them from?  please and thankyou.

**Comment by King-Icewind** [comment]
You can order it here: https://www.aliexpress.com/item/32855955475.html?spm=a2g0o.cart.0.0.5daf3c00KOZuk7&mp=1

If you happen to find it else where, make sure it comes with the lens.

**Comment by synaption** [comment]
nice, that one even comes with the lens.  thanks
