### ISSUE TITLE
Use ATmega32u4-AU to get factory DFU bootloader 

### ISSUE THREAD

**Issue by Duckle29** [ploopyco/classic-trackball#14]
Hi there. I noticed the docs talk about putting new firmware on the board using an Arduino nano as an ISP programmer. 
While that certainly would work, it's maybe a bit involved when there's already lots of cheap ISP programmer options available, like the USBtinyISP, the USBasp, and more.

That said, it shouldn't even be necessary, as all ATmega32u4 chips that come configured to use an external crystal (non RC versions), also ship with Atmel-DFU pre-programmed, and as such can be programmed over USB.

The datasheet has a mistake in Table 33.2, but I've gotten clarification that the statement on the first page of the datasheet 

> Parts using external XTAL clock are pre-programed with a default USB bootloader

is indeed correct:

![image](https://user-images.githubusercontent.com/2756925/74207306-59d65e00-4c7f-11ea-9307-9403ee77e036.png)

Figured I'd let you know for future batches :)

**Comment by ploopyco** [comment]
Thank you for looking into this.

Boards that we make already use the -AU variant (though they're shipped with mouse firmware already on-board). The instructions are written with the understanding that not everyone has access to these pre-programmed parts. This way, everyone making their own can program theirs, no matter what kind of chip they managed to get their hands on.
