### ISSUE TITLE
Handedness

### ISSUE THREAD

**Issue by hlieberman** [ploopyco/classic-trackball#2]
Hello!

I don't know if you've thought about handedness at all during this design, but how difficult of a process would it be to try and mirror the mouse over to create a left-handed version?

I imagine the PCB would also have to be mirrored, because the vertical section needs to be on the correct side, but would it just be a matter of flipping everything - stl's, and the pcb itself - along the y axis? Or is that going to spiral out of control into new and exciting problems?

**Comment by ploopyco** [comment]
Flipping the STLs is obviously a one-step process. The PCBs would have to be redone from scratch, since many components (TVS diodes, the MCU, the PMW3360, etc.) are not symmetrical. However, it wouldn't be a particularly difficult process - there aren't many EMC concerns to address.
