### ISSUE TITLE
REVD-BTU mod doesn't fit ball

### ISSUE THREAD

**Issue by Alistair1231** [ploopyco/classic-trackball#29]
Hi! I let someone print me the [REVD version](https://github.com/ploopyco/classic-trackball/blob/master/hardware/Mechanicals-BTU-Mod/STL/Ploopy-Top-REVD-BTU.stl) of the BTU mod, 
but the ball doesn't fit. With or without the BTUs in place. The hole seems too small..
Here are some pictures comparing the original top part with the new BTU part. Am I doing something wrong? Should I sand down the new part?
I believe @gbrnt designed this, I couldn't make an issue on his fork however.

<details>
  <summary>Click to view the images!</summary>
  
![image](https://user-images.githubusercontent.com/26165288/159007455-17105269-9914-46d9-beec-a1e4104e6b1e.png)
![image](https://user-images.githubusercontent.com/26165288/159007480-f208fe72-e06f-451a-a7cf-4a858835a280.png)
![image](https://user-images.githubusercontent.com/26165288/159007714-23e5fd48-a224-4b9d-9659-514bd8852e71.png)
![image](https://user-images.githubusercontent.com/26165288/159007741-10619c38-b5fb-49e4-8a2a-2687b44f21b0.png)
![image](https://user-images.githubusercontent.com/26165288/159009047-b7bdb636-b0ec-41bb-a131-670e2d22e29d.png)
![image](https://user-images.githubusercontent.com/26165288/159009063-82d930e7-5459-4f48-8a99-012dcfaf52ec.png)
</details>

UPDATE:
I sanded the inner part down, and also bought a 44.5mm billiard ball. Though there are still issues and I think the model is of the wrong size! Here are some images and videos regarding the mouse, which shows the way it's too small. https://photos.app.goo.gl/rMXwHFF1sCEd3Zp79

The person who printed the model for me gave me some additional insight as well! First of all, it seems unlikely that the issue was in the print. The person in question has according to his own statements, 8 years experience with 3d printers and a professional 3d printer that allows for 1x1x1m prints, also

    the tolerance is 0.01 mm from the printer which is very accurate. so the model can only deviate from the drawing by 0.01 and that is not noticeable in the print. I think something about the drawing is wrong. but what struck me is that both drawings I received were exactly the same size.

He also sent me an image comparing the model to the original revd top stl model from github and there is indeed a difference in length of the model visible.
![image](https://user-images.githubusercontent.com/26165288/159576069-49299ddc-0739-4c83-8ae5-c3543a0ae4c2.png)

My conclusion at this point is thus, that the BTU model has to be increased in size. Though I would like some other professional have a look at it. Especially [/u/FredCompany](https://old.reddit.com/u/FredCompany) / @gbrnt
since he seems to have created the model.

**Comment by gbrnt** [comment]
As mentioned in the reddit comments about this, this is because I missed something when making the REVC/REVD changes to the BTU mod. In your screenshot you can see that the REVD top has a much wider hole, while on the BTU top the curve extends further over the ball. I should be able to fix this.

Also, in your screenshot I don't think that's the REVD BTU top - it doesn't have the extra piece that hides the BTU. That was an earlier version. It's not the cause of your issue as the one you've printed isn't the same one that's in the screenshot.

**Comment by gbrnt** [comment]
It looks like I lost track of versions at some point (because my original Rhino files aren't tracked in Git since they're large) and applied the REVD changes to the REVA BTU top instead of the REVD BTU top. There's a bit of a mess for me to sort out here.

**Comment by gbrnt** [comment]
This should be fixed in [this commit in my fork of the repo](https://github.com/gbrnt/ploopy-classic/commit/25cbf3994e283b2e497a7e64d7ee26e42d14b42b). Please give it a try and report back, then I can ask ploopyco to merge it!

**Comment by Alistair1231** [comment]
Ok, Thanks! I will let this file be printed now. I will let you know how it turned out.

**Comment by Alistair1231** [comment]
> This should be fixed in [this commit in my fork of the repo](https://github.com/gbrnt/ploopy-classic/commit/25cbf3994e283b2e497a7e64d7ee26e42d14b42b). Please give it a try and report back, then I can ask ploopyco to merge it!

Now it fits! So, your changes worked! Thanks again!
