### ISSUE TITLE
Kicad & Solidworks files?

### ISSUE THREAD

**Issue by King-Icewind** [ploopyco/classic-trackball#3]
Do you have any Kicad files for the electronics and/or a Solidworks (or Autodesk Fusion 360) files for the casing?

**Comment by ploopyco** [comment]
The PCBs were done in Altium, and Altium has very few options to export in other formats. We're kind of stuck there.

We decided to release STEP files instead of application-specific design files for the mechanicals to ensure that the greatest number of applications could import them.
