### ISSUE TITLE
Purchase electronics only? 

### ISSUE THREAD

**Issue by JamesNewton** [ploopyco/classic-trackball#32]
Is there no option to purchase /just/ the electronics? I have printers, I have general hardware, I'd really like to just buy the PCB and maybe the ball? No?

**Comment by gbrnt** [comment]
I've seen this asked a few times on Reddit and the answer has been that the printed parts are so cheap in comparison to the rest there's not really any reason *not* to send them.

**Comment by cyberhuman** [comment]
They may be cheap but some people want to be sustainable and not generate more garbage than really needed :-(

**Comment by imme-emosol** [comment]
Would you buy the option if it was priced the same?

Somewhat related is that I would be interested in offering the extra parts from all recycled plastics.

**Comment by imme-emosol** [comment]
Issue can probably be closed
~ https://blog.ploopy.co/why-we-dont-offer-kits-without-3d-printed-parts-52 .
