### ISSUE TITLE
[suggestion] Middle/ringfinger trackball

### ISSUE THREAD

**Issue by krono** [ploopyco/classic-trackball#7]
simliar to #6, if there should be variants, one like the Logitech Cordless Trackman Optical T-RB22 would be cool. since the trackball is only shifted a bit to the right, this shouldn't be as complicated

**Comment by ploopyco** [comment]
I don't have any plans to make case variants.

I certainly have an opinion on the complexities of altering the enclosure, but if some enterprising individual was to come along and think to undertake the task, I wouldn't want to discourage them.
